import { ConversionRateData } from "@/types/conversion-rate";

export const mockConversionRateData: ConversionRateData = {
  stages: [
    {
      id: "new-customers",
      order: 1,
      title: "Khách hàng mới",
      total: 13,
      items: [
        { label: "Không có nguồn", value: 9, percentage: 69, indent: 0 },
        { label: "Thư điện tử", value: 0, indent: 0 },
        { label: "Sale tự tìm kiếm", value: 2, percentage: 15, indent: 0 },
        { label: "Tất cả", value: 1, percentage: 8, indent: 0 },
        { label: "Quảng cáo Google", value: 1, percentage: 8, indent: 0 },
        { label: "Tiếp thị Facebook", value: 1, percentage: 8, indent: 0 },
      ],
    },
    {
      id: "interactions",
      order: 2,
      title: "Tương tác",
      total: 122,
      items: [
        { label: "Thư điện tử", value: 0, indent: 0 },
        { label: "Tin nhắn", value: 0, indent: 0 },
        { label: "Zns", value: 0, indent: 0 },
        { label: "Gọi điện", value: 2, indent: 0 },
        { label: "Công việc", value: 101, indent: 0 },
        { label: "Trao đổi", value: 19, indent: 0 },
      ],
    },
    {
      id: "activities",
      order: 3,
      title: "Hoạt động",
      total: 101,
      items: [
        { label: "Theo dõi tin", value: 0, indent: 0 },
        { label: "Lịch đơn vệ sinh", value: 76, indent: 0 },
        { label: "Công việc nội bộ", value: 3, indent: 0 },
        { label: "Đặt lịch hẹn CN 2", value: 1, indent: 0 },
        { label: "VIP", value: 7, indent: 0 },
        { label: "Lịch hẹn", value: 1, indent: 0 },
        { label: "Theo loại công việc", value: 0, indent: 0 },
        { label: "Gọi lại", value: 41, indent: 0 },
        { label: "Đơn vệ sinh", value: 58, indent: 0 },
        { label: "Hẹn trải nghiệm", value: 1, indent: 0 },
        { label: "CƠ SỞ VẬT CHẤT", value: 1, indent: 0 },
      ],
    },
    {
      id: "orders",
      order: 4,
      title: "Đơn hàng",
      total: 15,
      items: [
        { label: "Đơn hàng", value: 15, indent: 0 },
        { label: "Báo giá", value: 0, indent: 0 },
        { label: "Hợp đồng", value: 0, indent: 0 },
        { label: "Xuất kho", value: 7, indent: 0 },
        { label: "Tỷ lệ số DH / Số KH mua hàng", value: 1.36, indent: 0 },
        { label: "Tần suất mua hàng", value: 0, indent: 0 },
        { label: "Một lần", value: 10, indent: 1 },
        { label: "Nhiều lần", value: 1, indent: 1 },
        { label: "Theo hợp động", value: 0, indent: 0 },
        { label: "Tái ký", value: 0, indent: 1 },
        { label: "Đã hết hạn", value: 0, indent: 1 },
        { label: "Thành toán", value: 0, indent: 0 },
        { label: "Đã thanh toán", value: 4, indent: 1 },
        { label: "Chưa thanh toán", value: 11, indent: 1 },
      ],
    },
    {
      id: "revenue",
      order: 5,
      title: "Doanh thu",
      total: 2700025999,
      isRevenue: true,
      items: [
        { label: "Không có nguồn", value: 2680025999, percentage: 99, indent: 0 },
        { label: "Sale tự tìm kiếm", value: 20000000, percentage: 1, indent: 0 },
        { label: "Thanh toán", value: 0, indent: 0 },
        { label: "Đã thanh toán", value: 41700000, percentage: 2, indent: 1 },
        { label: "Chưa thanh toán", value: 2658325999, percentage: 98, indent: 1 },
      ],
    },
  ],
};
