import { Customer, CustomerStatus } from "@/types/customer";

// Mock data for customers
export const mockCustomers: Customer[] = [
  {
    id: "1",
    orderNumber: 1,
    customerName: "Tuan Nguyen",
    phone: "08656554",
    address: "",
    salutation: "Anh",
    mobilePhone: "08656554",
    source: "",
    assignee: "Getfly Admin",
    relationship: "Đang thu",
    lastContactDate: undefined,
    createdDate: new Date("2024-01-15"),
    customerSource: "Website",
    gender: "Male",
    sessionCount: 0,
    remainingSessions: 0,
    status: CustomerStatus.NEW,
  },
  {
    id: "2",
    orderNumber: 2,
    customerName: "Nguyen Thi B",
    phone: "0845622197",
    address: "",
    salutation: "Chị",
    mobilePhone: "0845622197",
    source: "Facebook",
    assignee: "Getfly Admin",
    relationship: "Đang thu",
    lastContactDate: new Date("2024-03-20"),
    createdDate: new Date("2024-02-10"),
    customerSource: "Facebook",
    gender: "Female",
    sessionCount: 5,
    remainingSessions: 3,
    status: CustomerStatus.CONTACTED,
  },
  {
    id: "3",
    orderNumber: 3,
    customerName: "Công ty TNHH XYZ",
    phone: "0909123456",
    address: "123 Đường ABC, Quận XYZ",
    salutation: "Công ty",
    mobilePhone: "0987654321",
    source: "Referral",
    assignee: "Nhân viên cũ",
    relationship: "Đối tác",
    lastContactDate: new Date("2024-03-22"),
    createdDate: new Date("2024-01-20"),
    customerSource: "Giới thiệu",
    gender: "Other",
    sessionCount: 10,
    remainingSessions: 7,
    status: CustomerStatus.REGISTERED,
  },
  {
    id: "4",
    orderNumber: 4,
    customerName: "NVA",
    phone: "08978788767",
    address: "",
    salutation: "Anh",
    mobilePhone: "08978788767",
    source: "Google Ads",
    assignee: "Getfly Admin",
    relationship: "Đang thu",
    lastContactDate: undefined,
    createdDate: new Date("2024-03-01"),
    customerSource: "Google Ads",
    gender: "Male",
    sessionCount: 0,
    remainingSessions: 0,
    status: CustomerStatus.NEW,
  },
  {
    id: "5",
    orderNumber: 5,
    customerName: "0904808000",
    phone: "0904808000",
    address: "",
    salutation: "Anh",
    mobilePhone: "0904808000",
    source: "",
    assignee: "Getfly Admin",
    relationship: "Data2",
    lastContactDate: new Date("2024-03-15"),
    createdDate: new Date("2024-02-28"),
    customerSource: "Data Import",
    gender: "Male",
    sessionCount: 2,
    remainingSessions: 1,
    status: CustomerStatus.TESTED,
  },
  {
    id: "6",
    orderNumber: 6,
    customerName: "01234234234",
    phone: "01234234234",
    address: "Đà Nẵng",
    salutation: "Anh",
    mobilePhone: "065465423165",
    source: "Zalo",
    assignee: "Nhân viên cũ",
    relationship: "Thiện",
    lastContactDate: new Date("2024-03-18"),
    createdDate: new Date("2024-02-15"),
    customerSource: "Zalo",
    gender: "Male",
    sessionCount: 8,
    remainingSessions: 6,
    status: CustomerStatus.REGISTERED,
  },
  {
    id: "7",
    orderNumber: 7,
    customerName: "Chi A",
    phone: "09777777777",
    address: "",
    salutation: "Chị",
    mobilePhone: "09777777777",
    source: "Walk-in",
    assignee: "Getfly Admin",
    relationship: "Data3",
    lastContactDate: undefined,
    createdDate: new Date("2024-03-05"),
    customerSource: "Walk-in",
    gender: "Female",
    sessionCount: 0,
    remainingSessions: 0,
    status: CustomerStatus.CONSIDERING,
  },
  {
    id: "8",
    orderNumber: 8,
    customerName: "Cty TBL",
    phone: "0918120923",
    address: "",
    salutation: "Công ty",
    mobilePhone: "0918120923",
    source: "Email",
    assignee: "Getfly Admin",
    relationship: "Đang thu",
    lastContactDate: new Date("2024-03-21"),
    createdDate: new Date("2024-02-20"),
    customerSource: "Email Marketing",
    gender: "Other",
    sessionCount: 4,
    remainingSessions: 2,
    status: CustomerStatus.CONTACTED,
  },
  {
    id: "9",
    orderNumber: 9,
    customerName: "Cty TNHH AAAAAA",
    phone: "0919304956",
    address: "Nguyễn văn A",
    salutation: "Công ty",
    mobilePhone: "0919304955",
    source: "LinkedIn",
    assignee: "Getfly Admin",
    relationship: "Anh",
    lastContactDate: new Date("2024-03-19"),
    createdDate: new Date("2024-01-30"),
    customerSource: "LinkedIn",
    gender: "Other",
    sessionCount: 15,
    remainingSessions: 12,
    status: CustomerStatus.UPSELL,
  },
  {
    id: "10",
    orderNumber: 10,
    customerName: "Pham Thi Minh Thư",
    phone: "0797143810",
    address: "",
    salutation: "Chị",
    mobilePhone: "0797143810",
    source: "TikTok",
    assignee: "Getfly Admin",
    relationship: "Gửi",
    lastContactDate: undefined,
    createdDate: new Date("2024-03-10"),
    customerSource: "TikTok Ads",
    gender: "Female",
    sessionCount: 0,
    remainingSessions: 0,
    status: CustomerStatus.QUOTED,
  },
  {
    id: "11",
    orderNumber: 11,
    customerName: "Công Ty A",
    phone: "0336942483",
    address: "",
    salutation: "Công ty",
    mobilePhone: "0336942483",
    source: "Event",
    assignee: "Getfly Admin",
    relationship: "Đã B",
    lastContactDate: new Date("2024-03-23"),
    createdDate: new Date("2024-02-05"),
    customerSource: "Sự kiện",
    gender: "Other",
    sessionCount: 6,
    remainingSessions: 4,
    status: CustomerStatus.APPROACHED,
  },
  {
    id: "12",
    orderNumber: 12,
    customerName: "Thái Thị Thu Quyên",
    phone: "0847456128",
    address: "",
    salutation: "Chị",
    mobilePhone: "0847456128",
    source: "Hotline",
    assignee: "Getfly Admin",
    relationship: "Data3",
    lastContactDate: undefined,
    createdDate: new Date("2024-03-12"),
    customerSource: "Hotline",
    gender: "Female",
    sessionCount: 0,
    remainingSessions: 0,
    status: CustomerStatus.SURVEYED,
  },
  {
    id: "13",
    orderNumber: 13,
    customerName: "Nguyễn Văn Học",
    phone: "0901234567",
    address: "Hà Nội",
    salutation: "Anh",
    mobilePhone: "0901234567",
    source: "Facebook",
    assignee: "Getfly Admin",
    relationship: "Học viên",
    lastContactDate: new Date("2024-03-25"),
    createdDate: new Date("2024-01-10"),
    customerSource: "Facebook Ads",
    gender: "Male",
    sessionCount: 20,
    remainingSessions: 15,
    status: "studying" as any,
  },
  {
    id: "14",
    orderNumber: 14,
    customerName: "Lê Thị Mai",
    phone: "0912345678",
    address: "TP HCM",
    salutation: "Chị",
    mobilePhone: "0912345678",
    source: "Google",
    assignee: "Nhân viên A",
    relationship: "Học viên",
    lastContactDate: new Date("2024-02-15"),
    createdDate: new Date("2023-12-05"),
    customerSource: "Google Ads",
    gender: "Female",
    sessionCount: 30,
    remainingSessions: 0,
    status: "paused" as any,
  },
  {
    id: "15",
    orderNumber: 15,
    customerName: "Trần Văn Đạt",
    phone: "0923456789",
    address: "Đà Nẵng",
    salutation: "Anh",
    mobilePhone: "0923456789",
    source: "Zalo",
    assignee: "Getfly Admin",
    relationship: "Học viên",
    lastContactDate: new Date("2024-01-20"),
    createdDate: new Date("2023-10-15"),
    customerSource: "Zalo",
    gender: "Male",
    sessionCount: 40,
    remainingSessions: 0,
    status: "completed" as any,
  },
  {
    id: "16",
    orderNumber: 16,
    customerName: "Phạm Thị Lan",
    phone: "0934567890",
    address: "Hải Phòng",
    salutation: "Chị",
    mobilePhone: "0934567890",
    source: "Website",
    assignee: "Nhân viên B",
    relationship: "Học viên",
    lastContactDate: new Date("2024-03-10"),
    createdDate: new Date("2024-02-01"),
    customerSource: "Website",
    gender: "Female",
    sessionCount: 25,
    remainingSessions: 20,
    status: "transferred" as any,
  },
  {
    id: "17",
    orderNumber: 17,
    customerName: "Hoàng Văn Bảo",
    phone: "0945678901",
    address: "Cần Thơ",
    salutation: "Anh",
    mobilePhone: "0945678901",
    source: "TikTok",
    assignee: "Getfly Admin",
    relationship: "Học viên",
    lastContactDate: new Date("2024-02-28"),
    createdDate: new Date("2024-01-05"),
    customerSource: "TikTok",
    gender: "Male",
    sessionCount: 15,
    remainingSessions: 15,
    status: "on_hold" as any,
  },
  {
    id: "18",
    orderNumber: 18,
    customerName: "Ngô Thị Hương",
    phone: "0956789012",
    address: "Nha Trang",
    salutation: "Chị",
    mobilePhone: "0956789012",
    source: "Email",
    assignee: "Nhân viên C",
    relationship: "Học viên",
    lastContactDate: new Date("2024-01-10"),
    createdDate: new Date("2023-11-20"),
    customerSource: "Email",
    gender: "Female",
    sessionCount: 10,
    remainingSessions: 0,
    status: "cancelled" as any,
  },
  {
    id: "19",
    orderNumber: 19,
    customerName: "Đặng Văn Chờ",
    phone: "0967890123",
    address: "Vũng Tàu",
    salutation: "Anh",
    mobilePhone: "0967890123",
    source: "Walk-in",
    assignee: "Getfly Admin",
    relationship: "Học viên",
    lastContactDate: new Date("2024-03-20"),
    createdDate: new Date("2024-03-15"),
    customerSource: "Walk-in",
    gender: "Male",
    sessionCount: 8,
    remainingSessions: 5,
    status: "waiting_payment" as any,
  },
  {
    id: "20",
    orderNumber: 20,
    customerName: "Vũ Thị Nợ",
    phone: "0978901234",
    address: "Huế",
    salutation: "Chị",
    mobilePhone: "0978901234",
    source: "Referral",
    assignee: "Nhân viên D",
    relationship: "Học viên",
    lastContactDate: new Date("2024-02-25"),
    createdDate: new Date("2024-01-20"),
    customerSource: "Giới thiệu",
    gender: "Female",
    sessionCount: 12,
    remainingSessions: 8,
    status: "overdue" as any,
  },
  {
    id: "21",
    orderNumber: 21,
    customerName: "Bùi Văn Mới",
    phone: "0989012345",
    address: "Quy Nhơn",
    salutation: "Anh",
    mobilePhone: "0989012345",
    source: "Facebook",
    assignee: "Getfly Admin",
    relationship: "Mới",
    lastContactDate: new Date("2024-03-28"),
    createdDate: new Date("2024-03-28"),
    customerSource: "Facebook",
    gender: "Male",
    sessionCount: 0,
    remainingSessions: 0,
    status: "new_account" as any,
  },
  {
    id: "22",
    orderNumber: 22,
    customerName: "Lý Thị Học",
    phone: "0990123456",
    address: "Biên Hòa",
    salutation: "Chị",
    mobilePhone: "0990123456",
    source: "Google",
    assignee: "Nhân viên E",
    relationship: "Học viên",
    lastContactDate: new Date("2024-03-26"),
    createdDate: new Date("2024-02-10"),
    customerSource: "Google",
    gender: "Female",
    sessionCount: 18,
    remainingSessions: 12,
    status: "studying" as any,
  },
];
