import { CustomerJourneyData, JourneyCategory, JOURNEY_STAGES } from "@/types/customer-journey";

// Mock data for customer journey stages
export const mockCustomerJourneyData: CustomerJourneyData[] = [
  {
    category: JourneyCategory.AWARENESS,
    totalCount: 63,
    stages: [
      {
        id: JOURNEY_STAGES.DATA_MOI.id,
        name: JOURNEY_STAGES.DATA_MOI.name,
        description: JOURNEY_STAGES.DATA_MOI.description,
        count: 63,
        percentage: 30,
        color: JOURNEY_STAGES.DATA_MOI.color,
        category: JOURNEY_STAGES.DATA_MOI.category,
        order: 1,
      },
    ],
  },
  {
    category: JourneyCategory.DISCOVERY,
    totalCount: 83,
    stages: [
      {
        id: JOURNEY_STAGES.DA_TU_VAN.id,
        name: JOURNEY_STAGES.DA_TU_VAN.name,
        description: JOURNEY_STAGES.DA_TU_VAN.description,
        count: 7,
        percentage: 3,
        color: JOURNEY_STAGES.DA_TU_VAN.color,
        category: JOURNEY_STAGES.DA_TU_VAN.category,
        order: 1,
      },
      {
        id: JOURNEY_STAGES.DA_LIEN_HE.id,
        name: JOURNEY_STAGES.DA_LIEN_HE.name,
        count: 20,
        percentage: 10,
        color: JOURNEY_STAGES.DA_LIEN_HE.color,
        category: JOURNEY_STAGES.DA_LIEN_HE.category,
        order: 2,
      },
      {
        id: JOURNEY_STAGES.DA_TEST_DAU_VAO.id,
        name: JOURNEY_STAGES.DA_TEST_DAU_VAO.name,
        count: 16,
        percentage: 8,
        color: JOURNEY_STAGES.DA_TEST_DAU_VAO.color,
        category: JOURNEY_STAGES.DA_TEST_DAU_VAO.category,
        order: 3,
      },
    ],
  },
  {
    category: JourneyCategory.CONSIDERATION,
    totalCount: 50,
    stages: [
      {
        id: JOURNEY_STAGES.DANG_CAN_NHAC.id,
        name: JOURNEY_STAGES.DANG_CAN_NHAC.name,
        count: 50,
        percentage: 24,
        color: JOURNEY_STAGES.DANG_CAN_NHAC.color,
        category: JOURNEY_STAGES.DANG_CAN_NHAC.category,
        order: 1,
      },
      {
        id: JOURNEY_STAGES.KHONG_DANG_KI.id,
        name: JOURNEY_STAGES.KHONG_DANG_KI.name,
        count: 0,
        percentage: 0,
        color: JOURNEY_STAGES.KHONG_DANG_KI.color,
        category: JOURNEY_STAGES.KHONG_DANG_KI.category,
        order: 2,
      },
    ],
  },
  {
    category: JourneyCategory.SUCCESS,
    totalCount: 25,
    stages: [
      {
        id: JOURNEY_STAGES.CHUA_LIEN_HE_DUOC.id,
        name: JOURNEY_STAGES.CHUA_LIEN_HE_DUOC.name,
        count: 7,
        percentage: 3,
        color: JOURNEY_STAGES.CHUA_LIEN_HE_DUOC.color,
        category: JOURNEY_STAGES.CHUA_LIEN_HE_DUOC.category,
        order: 1,
      },
      {
        id: JOURNEY_STAGES.DA_DANG_KY.id,
        name: JOURNEY_STAGES.DA_DANG_KY.name,
        count: 18,
        percentage: 9,
        color: JOURNEY_STAGES.DA_DANG_KY.color,
        category: JOURNEY_STAGES.DA_DANG_KY.category,
        order: 2,
      },
    ],
  },
  {
    category: JourneyCategory.POST_SALES,
    totalCount: 15,
    stages: [
      {
        id: JOURNEY_STAGES.UPSELL.id,
        name: JOURNEY_STAGES.UPSELL.name,
        count: 15,
        percentage: 7,
        color: JOURNEY_STAGES.UPSELL.color,
        category: JOURNEY_STAGES.UPSELL.category,
        order: 1,
      },
    ],
  },
  {
    category: JourneyCategory.POST_SALES_ADVANCED,
    totalCount: 3,
    stages: [
      {
        id: JOURNEY_STAGES.KHAO_SAT.id,
        name: JOURNEY_STAGES.KHAO_SAT.name,
        count: 0,
        percentage: 0,
        color: JOURNEY_STAGES.KHAO_SAT.color,
        category: JOURNEY_STAGES.KHAO_SAT.category,
        order: 1,
      },
      {
        id: JOURNEY_STAGES.DOI_TAC.id,
        name: JOURNEY_STAGES.DOI_TAC.name,
        description: JOURNEY_STAGES.DOI_TAC.description,
        count: 1,
        percentage: 0,
        color: JOURNEY_STAGES.DOI_TAC.color,
        category: JOURNEY_STAGES.DOI_TAC.category,
        order: 2,
      },
      {
        id: JOURNEY_STAGES.HEN_THAT_BAI.id,
        name: JOURNEY_STAGES.HEN_THAT_BAI.name,
        count: 0,
        percentage: 0,
        color: JOURNEY_STAGES.HEN_THAT_BAI.color,
        category: JOURNEY_STAGES.HEN_THAT_BAI.category,
        order: 3,
      },
      {
        id: JOURNEY_STAGES.GUI_BAO_GIA.id,
        name: JOURNEY_STAGES.GUI_BAO_GIA.name,
        count: 2,
        percentage: 1,
        color: JOURNEY_STAGES.GUI_BAO_GIA.color,
        category: JOURNEY_STAGES.GUI_BAO_GIA.category,
        order: 4,
      },
      {
        id: JOURNEY_STAGES.DAU_VISA_HOAN_TAT.id,
        name: JOURNEY_STAGES.DAU_VISA_HOAN_TAT.name,
        count: 0,
        percentage: 0,
        color: JOURNEY_STAGES.DAU_VISA_HOAN_TAT.color,
        category: JOURNEY_STAGES.DAU_VISA_HOAN_TAT.category,
        order: 5,
      },
      {
        id: JOURNEY_STAGES.MAT_KHACH.id,
        name: JOURNEY_STAGES.MAT_KHACH.name,
        count: 0,
        percentage: 0,
        color: JOURNEY_STAGES.MAT_KHACH.color,
        category: JOURNEY_STAGES.MAT_KHACH.category,
        order: 6,
      },
      {
        id: JOURNEY_STAGES.DA_SU_DUNG_DICH_VU.id,
        name: JOURNEY_STAGES.DA_SU_DUNG_DICH_VU.name,
        count: 0,
        percentage: 0,
        color: JOURNEY_STAGES.DA_SU_DUNG_DICH_VU.color,
        category: JOURNEY_STAGES.DA_SU_DUNG_DICH_VU.category,
        order: 7,
      },
    ],
  },
];
